spring:
    profiles:
      # 申明使用哪个配置文件(dev,prod,test)
      # application.properties（默认读取）、
      # application-dev.properties（开发环境）、
      # application-prod.properties（生成环境）、
      # application-test.properties（测试环境） 
      active: dev

server:
  contextPath: /xiaozan-web-xiaozan
  port: 8080
  
springfox:
  documentation:
    swagger.v2.path: /api-docs
    swagger.v2.host: localhost:8080