#开发环境
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        name: xiaozan
        url: jdbc:mysql://localhost:3306/db_xiaozan
        username: root
        password: CFP5peaTAHiVixoYeqram5gcNR8p/EjsY5Sm0g+XFtOUvTOXV/LawLaIivNhOtyFn9TMxISaIOYR9gaL6lDgIQ==
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        maxActive: 20
        minIdle: 5
        maxWait: 60000
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: -1
        validationQueryTimeout: 15
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        config:
          decrypt: true
          decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMqE4gQ3B+/vqcXD7HsfTC3Oi8YYQKdDF8YdA4+KYWkoU3oK6fcT28YUmP+TWBzBPruKcERfDXQHo8hdm5TjXu0CAwEAAQ==
